# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LasTifToCsv
                                 A QGIS plugin
 LAS/TIF to CSV exporter
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-06-13
        copyright            : (C) 2026 by takemita
        email                : takeshi_mitarai@yahoo.co.jp
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LasTifToCsv class from file LasTifToCsv.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .las_tif_to_csv import LasTifToCsv
    return LasTifToCsv(iface)
